
create table public.car_models (
    car_model_id bigint generated by default as identity,
    car_model_name varchar(255) not null unique,
    primary key (car_model_id)
);

create table public.cars (
    manufacture_year integer not null,
    car_id bigint generated by default as identity,
    car_model_id bigint not null unique,
    category_id bigint not null,
    manufacturer_id bigint not null,
    primary key (car_id)
);

create table public.categories (
    category_id bigint generated by default as identity,
    category_name varchar(255) not null unique,
    primary key (category_id)
);

create table public.manufacturers (
    manufacturer_id bigint generated by default as identity,
    manufacturer_name varchar(255) not null unique,
    primary key (manufacturer_id)
);

alter table if exists public.cars
    add constraint Fk_car_model_id_cars foreign key (car_model_id)
    references public.car_models;

alter table if exists public.cars add constraint
    Fk_category_id_cars foreign key (category_id)
    references public.categories;

alter table if exists public.cars
    add constraint Fk_manufacturers_cars foreign key (manufacturer_id)
    references public.manufacturers;